#!/usr/bin/env python3
"""Snapshot the GitHub traffic API into a durable time series.

GitHub only retains 14 days of clone/view traffic. This script appends each
day's rows into metrics/traffic.json so the history survives past the window,
and records the API's own 14-day aggregate as a separate checkpoint series.

Why two series
--------------
The per-day `uniques` figures CANNOT be summed to get a total unique count —
the same person cloning on Monday and Thursday appears in both days. Summing
them inflates the number, sometimes badly.

So we store:

  * ``daily``    — raw per-day {count, uniques} rows, keyed by date. Honest for
                   ``count`` (a sum of daily counts IS the true total), and
                   useful for shape/trend on ``uniques``.
  * ``windows``  — a snapshot of the API's own 14-day aggregate, taken once per
                   run. Within a window GitHub has already deduplicated, so
                   ``uniques`` here is a real unique-visitor count for that
                   window. THIS is the number to quote.

Re-running on the same day is idempotent: daily rows are merged by date (later
snapshots win, since GitHub revises the current day upward as it accrues), and
at most one window checkpoint is kept per date.

Usage:
    GITHUB_TOKEN=<token with push/admin-read> python scripts/snapshot_traffic.py
    python scripts/snapshot_traffic.py --repo owner/name --out metrics/traffic.json
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

API = "https://api.github.com/repos/{repo}/traffic/{kind}"

NOTE = (
    "Auto-generated by scripts/snapshot_traffic.py. GitHub retains only 14 days "
    "of traffic; this file is the durable history. IMPORTANT: do not sum the "
    "per-day 'uniques' values — the same visitor appears in multiple days. Quote "
    "the 'windows' series instead, where GitHub has already deduplicated within "
    "each 14-day window."
)


def fetch(repo: str, kind: str, token: str) -> dict:
    """Fetch one traffic endpoint. `kind` is 'clones' or 'views'."""
    req = urllib.request.Request(
        API.format(repo=repo, kind=kind),
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "amnesic-traffic-snapshot",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        if exc.code == 403:
            sys.exit(
                f"403 from /traffic/{kind}. The traffic API needs push access — "
                "the default GITHUB_TOKEN is often not enough. Create a "
                "fine-grained PAT with 'Administration: Read-only' on this repo "
                "and store it as the METRICS_TOKEN secret."
            )
        sys.exit(f"HTTP {exc.code} from /traffic/{kind}: {exc.read().decode()[:200]}")


def load(path: Path) -> dict:
    if not path.exists():
        return {"note": NOTE, "repo": None, "daily": {"clones": {}, "views": {}}, "windows": []}
    data = json.loads(path.read_text(encoding="utf-8"))
    data.setdefault("daily", {"clones": {}, "views": {}})
    data.setdefault("windows", [])
    return data


def merge_daily(existing: dict, payload: dict, kind: str) -> int:
    """Merge API rows into the daily map, keyed by date. Returns new-day count."""
    rows = payload.get(kind, [])
    bucket = existing["daily"].setdefault(kind, {})
    new_days = 0
    for row in rows:
        # "2026-08-02T00:00:00Z" -> "2026-08-02"
        day = row["timestamp"][:10]
        if day not in bucket:
            new_days += 1
        # Later snapshots win: GitHub revises the current day upward as it accrues.
        bucket[day] = {"count": row["count"], "uniques": row["uniques"]}
    return new_days


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "SurajKGoyal/amnesic"))
    ap.add_argument("--out", default="metrics/traffic.json")
    args = ap.parse_args()

    token = os.environ.get("METRICS_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        sys.exit("Set METRICS_TOKEN or GITHUB_TOKEN.")

    clones = fetch(args.repo, "clones", token)
    views = fetch(args.repo, "views", token)

    path = Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = load(path)
    data["note"] = NOTE
    data["repo"] = args.repo

    new_clone_days = merge_daily(data, clones, "clones")
    new_view_days = merge_daily(data, views, "views")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    checkpoint = {
        "snapshot_date": today,
        "window_days": 14,
        "clones_total": clones.get("count", 0),
        "clones_uniques": clones.get("uniques", 0),
        "views_total": views.get("count", 0),
        "views_uniques": views.get("uniques", 0),
    }
    # One checkpoint per date — re-running today replaces today's.
    data["windows"] = [w for w in data["windows"] if w.get("snapshot_date") != today]
    data["windows"].append(checkpoint)
    data["windows"].sort(key=lambda w: w["snapshot_date"])

    # Cumulative clone COUNT is safe to sum (unlike uniques).
    data["totals"] = {
        "days_recorded": len(data["daily"]["clones"]),
        "clones_all_time": sum(r["count"] for r in data["daily"]["clones"].values()),
        "views_all_time": sum(r["count"] for r in data["daily"]["views"].values()),
        "first_day": min(data["daily"]["clones"], default=None),
        "last_day": max(data["daily"]["clones"], default=None),
    }

    path.write_text(json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    print(
        f"{args.repo}: +{new_clone_days} clone day(s), +{new_view_days} view day(s). "
        f"14d window: {checkpoint['clones_uniques']} unique cloners, "
        f"{checkpoint['views_uniques']} unique visitors. "
        f"History: {data['totals']['days_recorded']} days."
    )


if __name__ == "__main__":
    main()
